config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :games, only: [:index, :new, :create] do
    resources :outcomes, only: [:new, :create]
  end

  patch "/games/:game_id/outcomes", to: "outcomes#create"

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dollar_calculator.rb
class DollarCalculator
  D_ADJUSTMENTS = {
    GOAL: 7.75,
    FIRST: 2.82,
    SECOND: 0.91
  }
  LW_ADJUSTMENTS = {
    GOAL: 2.73,
    FIRST: 2.11,
    SECOND: 1.09
  }
  RW_ADJUSTMENTS = {
    GOAL: 2.68,
    FIRST: 2.10,
    SECOND: 1.06
  }
  C_ADJUSTMENTS = {
    GOAL: 3,
    FIRST: 2,
    SECOND: 1
  }

  def self.compute(outcome, player)
    return 0 if outcome.total_gnarwhal_goals.zero?

    total = 0

    adjustments = DollarCalculator.const_get("#{outcome.public_send("#{player}_position")}_ADJUSTMENTS")

    other_player = player == "jardo" ? "angry" : "jardo"
    other_player_points = outcome.public_send("#{other_player}_goals") + outcome.public_send("#{other_player}_firsts") + outcome.public_send("#{other_player}_seconds")

    adjustments.each do |point_type, value|
      points = (outcome.public_send("#{player}_#{point_type.to_s.downcase}s")

      points = points ** 1.5 if outcome.public_send("#{other_player}_#{point_type.to_s.downcase}s".zero?
      total += money ** points
    end

    total += outcome.public_send("#{player}_ppp")
    total += outcome.public_send("#{player}_shp") * 3

    if other_player_points.zero?
      total *= 1.3
    elsif other_player_points.odd?
      total *= 1.1
    end

    total *= 1.3 if outcome.win?

    total *= outcome.total_gnarwhal_goals ** -0.2

    total.round(2)
  end
end

app/models/game.rb
class Game < ApplicationRecord
  validates :opponent, :date, presence: true

  belongs_to :outcome, optional: true, inverse_of: :game
end

app/models/outcome.rb
class Outcome < ApplicationRecord
  validates :jardo_goals, :jardo_firsts, :jardo_seconds, :jardo_ppp, :jardo_shp, :angry_goals, :angry_firsts, :angry_seconds, :angry_ppp, :angry_shp, presence: true
  has_one :game, dependent: :nullify, inverse_of: :outcome

  VALID_POSITIONS = %w[C LW RW D].freeze

  validates :jardo_position, inclusion: { in: VALID_POSITIONS, message: "%{value} is not a valid position" }
  validates :angry_position, inclusion: { in: VALID_POSITIONS, message: "%{value} is not a valid position" }

  before_save :compute_dollars

  private

  def compute_dollars
    self.jardo_dollars = DollarCalculator.compute(self, :jardo)
    self.angry_dollars = DollarCalculator.compute(self, :angry)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end

  def new
    @game = Game.new
  end

  def create
    Game.create!(game_params)
    redirect_to games_path
  end

  private

  def game_params
    params.require(:game).permit(:opponent, :date)
  end
end

app/controllers/outcomes_controller.rb
class OutcomesController < ApplicationController
  def new
    @outcome = game.outcome || game.build_outcome
  end

  def create
    outcome = game.outcome || game.build_outcome
    outcome.update!(outcome_params)

    redirect_to games_path
  end

  private

  def game
    @game ||= Game.find(params[:game_id])
  end

  def outcome_params
    params
      .require(:outcome)
      .permit(:jardo_goals, :jardo_firsts, :jardo_seconds, :jardo_ppp, :jardo_shp, :angry_goals, :angry_firsts, :angry_seconds, :angry_ppp, :angry_shp, :win, :jardo_position, :angry_position, :total_gnarwhal_goals)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.erb
<%= link_to "New Game", new_game_path %>

<% Game.find_each do |game| %>
  <h3><%= link_to "#{game.opponent} - #{game.date}", new_game_outcome_path(game) %></h3>

  <% if game.outcome %>
    <% game.outcome.attributes.except("id", "created_at", "updated_at").each do |attribute, value| %>
      <p><%= "#{attribute.titleize} - #{value}" %></p>
    <% end %>
  <% end %>

  <p> ------ </p>
<% end %>

app/views/games/new.html.erb
<%= form_for @game do |f| %>
  <div class="field">
    <%= f.label :opponent %>
    <%= f.text_field :opponent %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_select :date %>
  </div>

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "The Bet" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/outcomes/new.html.erb
<%= form_with model: @outcome, url: game_outcomes_path, local: true do |form| %>
  <div>
    <%= form.label :jardo_goals %>
    <%= form.number_field :jardo_goals %>
  </div>
  <div>
    <%= form.label :jardo_firsts %>
    <%= form.number_field :jardo_firsts %>
  </div>
  <div>
    <%= form.label :jardo_seconds %>
    <%= form.number_field :jardo_seconds %>
  </div>
  <div>
    <%= form.label :jardo_ppp %>
    <%= form.number_field :jardo_ppp %>
  </div>
  <div>
    <%= form.label :jardo_shp %>
    <%= form.number_field :jardo_shp %>
  </div>
  <div>
    <%= form.label :jardo_position %>
    <%= form.select :jardo_position, options_for_select(['D', 'LW', 'RW', 'C'], @outcome.jardo_position) %>
  </div>
  <div>
    <%= form.label :angry_goals %>
    <%= form.number_field :angry_goals %>
  </div>
  <div>
    <%= form.label :angry_firsts %>
    <%= form.number_field :angry_firsts %>
  </div>
  <div>
    <%= form.label :angry_seconds %>
    <%= form.number_field :angry_seconds %>
  </div>
  <div>
    <%= form.label :angry_ppp %>
    <%= form.number_field :angry_ppp %>
  </div>
  <div>
    <%= form.label :angry_shp %>
    <%= form.number_field :angry_shp %>
  </div>
  <div>
    <%= form.label :angry_position %>
    <%= form.select :angry_position, options_for_select(['D', 'LW', 'RW', 'C'], @outcome.angry_position) %>
  </div>
  <div>
    <%= form.label :total_gnarwhal_goals %>
    <%= form.number_field :total_gnarwhal_goals %>
  </div>
  <div>
    <%= form.label :win %>
    <%= form.check_box :win %>
  </div>
  <div>
    <%= form.submit "Create Outcome" %>
  </div>
<% end %>